### ISSUE TITLE
Submission format

### ISSUE THREAD

**Issue by rikingurditta** [dilevin/CSC2549-a1-mass-spring-1d#10]
Hello! On MarkUs, there's a list of required files:
![image](https://user-images.githubusercontent.com/19874469/93958756-326f6580-fd25-11ea-9f2f-f7674d8530c7.png)
Should we submit only these files, or the whole project in the MarkUs repo? Just want to know so I can submit the preferred way now and going forward. Thanks in advance!

**Comment by honglin-c** [comment]
Only the required files are needed. :)
